# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - capaciti-front-app-web

env:
  REACT_APP_GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.REACT_APP_GOOGLE_APPLICATION_CREDENTIALS}}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: azure/login@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_2f5458227ff44fdcb93133ca7aeb9247 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9b03bc28d3eb44c7a0fb5598defcc625 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_2f5458227ff44fdcb93133ca7aeb9247 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'capaciti-front-app-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_44a81cdfb0374bf48c7478875b653217 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_2f5458227ff44fdcb93133ca7aeb9247 }}/appsvc/staticsite:${{ github.sha }}'
