# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - capaciti-fron-app

env:
  REACT_APP_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.REACT_APP_GOOGLE_APPLICATION_CREDENTIALS }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_c4bad988562844e0bfc7cf08944817be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e85c6a69a85740fca0e2fecb862fd8e5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c4bad988562844e0bfc7cf08944817be }}/node:${{ github.sha }}
        file: ./capaciti-front/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'capaciti-fron-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0d850ca2decc4cddaee1152408b39e35 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c4bad988562844e0bfc7cf08944817be }}/node:${{ github.sha }}'
